{
 "title": "IPMI",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Voltage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ipmi_voltage_volts", "legendFormat": "{{ name }}" }
   ]
  },
  {
   "title": "Fan Speed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ipmi_fan_speed_rpm", "legendFormat": "{{ name }}" }
   ]
  },
  {
   "title": "Temperture",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ipmi_temperature_celsius", "legendFormat": "{{ name }}" }
   ]
  },
  {
   "title": "Chassis Intrusion",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ipmi_sensor_state", "legendFormat": "{{ name }}" }
   ]
  }
 ]
}