apiVersion: v1
kind: Service
metadata:
  name: ipmi-exporter
  namespace: ipmi-exporter
  labels:
    app: ipmi-exporter
spec:
  clusterIP: None
  ports:
  - name: metrics
    port: 9290
    protocol: TCP
    targetPort: 9290
  selector:
    app: ipmi-exporter
